// love/src/components/consumer-analytics/InsightsCard.tsx
import { Lightbulb } from 'lucide-react';

interface InsightsCardProps {
  insights: string[];
  title?: string;
}

export function InsightsCard({ insights, title = "Key Insights" }: InsightsCardProps) {
  return (
    <div className="bg-card border border-border rounded-xl p-4">
      <div className="flex items-center gap-2 mb-3">
        <Lightbulb className="h-5 w-5 text-primary" />
        <h4 className="text-sm font-semibold text-foreground">{title}</h4>
      </div>
      <ul className="space-y-2">
        {insights.map((insight, index) => (
          <li key={index} className="flex items-start gap-2 text-sm text-muted-foreground">
            <span className="text-primary mt-1">•</span>
            <span>{insight}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

// frontend/src/app/components/insights-card/insights-card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-insights-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './insights-card.component.html',
  styleUrl: './insights-card.component.css'
})
export class InsightsCardComponent {
  @Input() insights: string[] = [];
  @Input() title: string = 'Key Insights';
}

<div class="bg-card border rounded-xl p-4" [style.border-color]="'var(--border-color)'" [style.background-color]="'var(--bg-card)'">
  <div class="flex items-center gap-2 mb-3">
    <svg class="h-5 w-5" [style.color]="'var(--accent-color)'" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"></path>
    </svg>
    <h4 class="text-sm font-semibold" [style.color]="'var(--text-primary)'">{{ title }}</h4>
  </div>
  <ul class="space-y-2">
    <li *ngFor="let insight of insights" class="flex items-start gap-2 text-sm" [style.color]="'var(--text-secondary)'">
      <span [style.color]="'var(--accent-color)'" class="mt-1">•</span>
      <span>{{ insight }}</span>
    </li>
  </ul>
</div>
