// frontend/src/app/pages/consumer-data-analysis/consumer-data-analysis.component.ts
import { Component, OnInit, AfterViewInit, QueryList, ViewChildren } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { ConsumerAnalyticsDataService, 
  AbnormalConsumptionSummary, ConsumptionCase, 
  ZeroConsumptionMetric, ZeroConsumptionCategory, ZeroConsumptionConsumer,
  ConsumptionDropSummary, ConsumptionDropConsumer,
  LowConsumptionSummary, LowConsumptionConsumer,
  LowerThanExpectedConsumer,
  BucketLogic, ConsumerProfile, BucketSummary,
  CommunicationGapSummary, CommunicationAgeingCategory, CommunicationCircleBreakdown,
  CommunicationMeterDetail, CommunicationRootCause, CommunicationActionTracker,
  ChartDataPoint } from '../../services/consumer-analytics-data.service';
import { TopicSectionComponent } from '../../components/topic-section/topic-section.component';
import { ThemeService } from '../../services/theme.service';
import { BasePageLayoutComponent } from '../../components/base-page-layout/base-page-layout.component';
import { SummaryTilesComponent } from '../../components/summary-tiles/summary-tiles.component';
import { DataTableComponent, Column } from '../../components/data-table/data-table.component';
import { StatusBadgeComponent } from '../../components/status-badge/status-badge.component';
import { InsightsCardComponent } from '../../components/insights-card/insights-card.component';
import { BucketLogicTableComponent, BucketSummaryTableComponent } from '../../components/bucket-table/bucket-table.component';
import { ChartPlaceholderComponent } from '../../components/chart-placeholder/chart-placeholder.component';

@Component({
  selector: 'app-consumer-data-analysis',
  standalone: true,
  imports: [
    CommonModule, 
    RouterModule,
    TopicSectionComponent,
    BasePageLayoutComponent,
    SummaryTilesComponent,
    DataTableComponent,
    StatusBadgeComponent,
    InsightsCardComponent,
    BucketLogicTableComponent,
    BucketSummaryTableComponent,
    ChartPlaceholderComponent
  ],
  templateUrl: './consumer-data-analysis.component.html',
  styleUrl: './consumer-data-analysis.component.css'
})
export class ConsumerDataAnalysisComponent implements OnInit, AfterViewInit {
  @ViewChildren(TopicSectionComponent) topicSections!: QueryList<TopicSectionComponent>;
  // Topic 1
  abnormalConsumptionSummary: AbnormalConsumptionSummary[] = [];
  highConsumptionCases: ConsumptionCase[] = [];
  lowConsumptionCases: ConsumptionCase[] = [];
  spikeChartData: ChartDataPoint[] = [];
  dropChartData: ChartDataPoint[] = [];

  // Topic 2
  zeroConsumptionMetrics: ZeroConsumptionMetric[] = [];
  zeroConsumptionCategories: ZeroConsumptionCategory[] = [];
  zeroConsumptionConsumers: ZeroConsumptionConsumer[] = [];
  zeroConsumptionTrendData: ChartDataPoint[] = [];
  circleZeroConsumptionData: ChartDataPoint[] = [];

  // Topic 3
  consumptionDropSummary: ConsumptionDropSummary[] = [];
  consumptionDropConsumers: ConsumptionDropConsumer[] = [];

  // Topic 4
  lowConsumptionSummary: LowConsumptionSummary[] = [];
  lowConsumptionConsumers: LowConsumptionConsumer[] = [];

  // Topic 5
  lowerThanExpectedConsumers: LowerThanExpectedConsumer[] = [];

  // Topic 7
  bucketLogic: BucketLogic[] = [];
  consumerProfiles: ConsumerProfile[] = [];
  bucketSummary: BucketSummary[] = [];

  // Topic 8
  communicationGapSummary: CommunicationGapSummary[] = [];
  communicationAgeingCategories: CommunicationAgeingCategory[] = [];
  communicationCircleBreakdown: CommunicationCircleBreakdown[] = [];
  communicationMeterDetails: CommunicationMeterDetail[] = [];
  communicationRootCauses: CommunicationRootCause[] = [];
  communicationActionTracker: CommunicationActionTracker[] = [];

  // Column definitions for tables
  highConsumptionColumns: Column<ConsumptionCase>[] = [];
  lowConsumptionColumns: Column<ConsumptionCase>[] = [];
  zeroConsumptionCategoryColumns: Column<ZeroConsumptionCategory & { id: string }>[] = [];
  zeroConsumptionConsumerColumns: Column<ZeroConsumptionConsumer>[] = [];
  consumptionDropSummaryColumns: Column<ConsumptionDropSummary & { id: string }>[] = [];
  consumptionDropConsumerColumns: Column<ConsumptionDropConsumer>[] = [];
  lowConsumptionSummaryColumns: Column<LowConsumptionSummary & { id: string }>[] = [];
  lowConsumptionConsumerColumns: Column<LowConsumptionConsumer>[] = [];
  lowerThanExpectedColumns: Column<LowerThanExpectedConsumer>[] = [];
  consumerProfileColumns: Column<ConsumerProfile>[] = [];
  communicationAgeingCategoryColumns: Column<CommunicationAgeingCategory & { id: string }>[] = [];
  communicationCircleBreakdownColumns: Column<CommunicationCircleBreakdown>[] = [];
  communicationMeterDetailColumns: Column<CommunicationMeterDetail>[] = [];
  communicationRootCauseColumns: Column<CommunicationRootCause & { id: string }>[] = [];
  communicationActionTrackerColumns: Column<CommunicationActionTracker>[] = [];

  constructor(
    private dataService: ConsumerAnalyticsDataService,
    private themeService: ThemeService
  ) {}

  ngAfterViewInit() {
    // ViewChildren is available after view init
  }

  onTopicSectionOpened(openedSection: TopicSectionComponent) {
    // Close all other sections
    if (this.topicSections) {
      this.topicSections.forEach(section => {
        if (section !== openedSection) {
          section.close();
        }
      });
    }
  }

  ngOnInit() {
    // Load Topic 1 data
    this.abnormalConsumptionSummary = this.dataService.getAbnormalConsumptionSummary();
    this.highConsumptionCases = this.dataService.getHighConsumptionCases();
    this.lowConsumptionCases = this.dataService.getLowConsumptionCases();
    this.spikeChartData = this.dataService.getSpikeChartData();
    this.dropChartData = this.dataService.getDropChartData();

    // Load Topic 2 data
    this.zeroConsumptionMetrics = this.dataService.getZeroConsumptionMetrics();
    this.zeroConsumptionCategories = this.dataService.getZeroConsumptionCategories();
    this.zeroConsumptionConsumers = this.dataService.getZeroConsumptionConsumers();
    this.zeroConsumptionTrendData = this.dataService.getZeroConsumptionTrendData();
    this.circleZeroConsumptionData = this.dataService.getCircleZeroConsumptionData();

    // Load Topic 3 data
    this.consumptionDropSummary = this.dataService.getConsumptionDropSummary();
    this.consumptionDropConsumers = this.dataService.getConsumptionDropConsumers();

    // Load Topic 4 data
    this.lowConsumptionSummary = this.dataService.getLowConsumptionSummary();
    this.lowConsumptionConsumers = this.dataService.getLowConsumptionConsumers();

    // Load Topic 5 data
    this.lowerThanExpectedConsumers = this.dataService.getLowerThanExpectedConsumers();

    // Load Topic 7 data
    this.bucketLogic = this.dataService.getBucketLogic();
    this.consumerProfiles = this.dataService.getConsumerProfiles();
    this.bucketSummary = this.dataService.getBucketSummary();

    // Load Topic 8 data
    this.communicationGapSummary = this.dataService.getCommunicationGapSummary();
    this.communicationAgeingCategories = this.dataService.getCommunicationAgeingCategories();
    this.communicationCircleBreakdown = this.dataService.getCommunicationCircleBreakdown();
    this.communicationMeterDetails = this.dataService.getCommunicationMeterDetails();
    this.communicationRootCauses = this.dataService.getCommunicationRootCauses();
    this.communicationActionTracker = this.dataService.getCommunicationActionTracker();

    // Define columns
    this.setupColumns();
  }

  setupColumns() {
    this.highConsumptionColumns = [
      { header: 'Circle', accessor: 'circle' },
      { header: 'Division', accessor: 'division' },
      { header: 'Subdivision', accessor: 'subdivision' },
      { header: 'Consumer No.', accessor: 'consumerNo', className: 'font-mono text-[#3c83f6]' },
      { header: 'Avg (3 mo)', accessor: 'avgConsumption', className: 'text-right' },
      { header: 'Current', accessor: 'currentMonth', className: 'text-right' },
      { header: '% Change', accessor: (row) => `+${row.percentChange}%`, className: 'text-right text-emerald-500' },
      { header: 'Status', accessor: (row) => ({ status: row.meterStatus, variant: this.getStatusVariant(row.meterStatus) }), className: '' },
      { header: 'Remarks', accessor: 'remarks' },
    ];

    this.lowConsumptionColumns = [
      { header: 'Circle', accessor: 'circle' },
      { header: 'Division', accessor: 'division' },
      { header: 'Subdivision', accessor: 'subdivision' },
      { header: 'Consumer No.', accessor: 'consumerNo', className: 'font-mono text-[#3c83f6]' },
      { header: 'Avg (3 mo)', accessor: 'avgConsumption', className: 'text-right' },
      { header: 'Current', accessor: 'currentMonth', className: 'text-right' },
      { header: '% Change', accessor: (row) => `${row.percentChange}%`, className: 'text-right text-red-500' },
      { header: 'Status', accessor: (row) => ({ status: row.meterStatus, variant: this.getStatusVariant(row.meterStatus) }), className: '' },
      { header: 'Remarks', accessor: 'remarks' },
    ];

    this.zeroConsumptionCategoryColumns = [
      { header: 'Category', accessor: 'category' },
      { header: 'Count', accessor: 'count', className: 'text-right' },
      { header: '% of Total', accessor: (row) => `${row.percentage}%`, className: 'text-right' },
      { header: 'Comments', accessor: 'comments' },
    ];

    this.zeroConsumptionConsumerColumns = [
      { header: 'Circle', accessor: 'circle' },
      { header: 'Division', accessor: 'division' },
      { header: 'Consumer No.', accessor: 'consumerNo', className: 'font-mono text-[#3c83f6]' },
      { header: 'Meter Serial', accessor: 'meterSerialNo' },
      { header: 'Last Data', accessor: 'lastDataReceived' },
      { header: 'Last kWh', accessor: 'lastConsumption', className: 'text-right' },
      { header: 'Status', accessor: (row) => ({ status: row.communicationStatus, variant: this.getStatusVariant(row.communicationStatus) }), className: '' },
      { header: 'Remarks', accessor: 'remarks' },
    ];

    this.consumptionDropSummaryColumns = [
      { header: 'Parameter', accessor: 'parameter' },
      { header: 'Count of Consumers', accessor: 'consumerCount', className: 'text-right' },
      { header: 'Total Drop (kWh)', accessor: 'totalDrop', className: 'text-right' },
      { header: 'Avg. % Drop', accessor: (row) => `${row.avgDropPercent}%`, className: 'text-right text-red-500' },
    ];

    this.consumptionDropConsumerColumns = [
      { header: 'S.No', accessor: 'sNo' },
      { header: 'Consumer No.', accessor: 'consumerNo', className: 'font-mono text-[#3c83f6]' },
      { header: 'Name', accessor: 'consumerName' },
      { header: 'Current', accessor: 'currentMonth', className: 'text-right' },
      { header: 'Same Month LY', accessor: 'sameMonthLastYear', className: 'text-right' },
      { header: 'Last Month', accessor: 'lastMonth', className: 'text-right' },
      { header: '% Drop', accessor: (row) => `${row.dropPercent}%`, className: 'text-right text-red-500' },
    ];

    this.lowConsumptionSummaryColumns = [
      { header: 'Category', accessor: 'category' },
      { header: 'No. of Consumers', accessor: 'consumerCount', className: 'text-right' },
      { header: '% of Total', accessor: (row) => row.percentOfTotal > 0 ? `${row.percentOfTotal}%` : '—', className: 'text-right' },
    ];

    this.lowConsumptionConsumerColumns = [
      { header: 'S.No', accessor: 'sNo' },
      { header: 'Consumer No.', accessor: 'consumerNo', className: 'font-mono text-[#3c83f6]' },
      { header: 'Name', accessor: 'name' },
      { header: 'SL (kW)', accessor: 'sanctionedLoad', className: 'text-right' },
      { header: 'Avg Monthly', accessor: 'avgMonthlyConsumption', className: 'text-right' },
      { header: 'Expected', accessor: 'expectedConsumption', className: 'text-right' },
      { header: '% Deviation', accessor: (row) => `${row.deviation}%`, className: 'text-right text-red-500' },
      { header: 'Status', accessor: (row) => ({ status: row.meterStatus, variant: this.getStatusVariant(row.meterStatus) }), className: '' },
    ];

    this.lowerThanExpectedColumns = [
      { header: 'Sr.No', accessor: 'srNo' },
      { header: 'Consumer No.', accessor: 'consumerNo', className: 'font-mono text-[#3c83f6]' },
      { header: 'Name', accessor: 'consumerName' },
      { header: 'Meter No.', accessor: 'meterNo' },
      { header: 'Avg LY (kWh)', accessor: 'avgMonthlyLastYear', className: 'text-right' },
      { header: 'Current (kWh)', accessor: 'currentMonthConsumption', className: 'text-right' },
      { header: '% Deviation', accessor: (row) => `${row.deviation}%`, className: 'text-right text-red-500' },
      { header: 'Expected Range', accessor: 'expectedRange' },
      { header: 'Remarks', accessor: 'remarks' },
    ];

    this.consumerProfileColumns = [
      { header: 'S.No', accessor: 'sNo' },
      { header: 'Consumer No.', accessor: 'consumerNo', className: 'font-mono text-[#3c83f6]' },
      { header: 'Name', accessor: 'name' },
      { header: 'Category', accessor: 'category' },
      { header: 'SL (kW)', accessor: 'sanctionedLoad', className: 'text-right' },
      { header: 'Avg MD', accessor: 'avgMD', className: 'text-right' },
      { header: 'Bucket', accessor: (row) => ({ 
        status: row.bucket, 
        variant: row.bucket.includes('High') ? 'danger' : row.bucket.includes('Medium') ? 'warning' : 'success' 
      }), className: '' },
      { header: 'Tamper', accessor: 'tamperEvents', className: 'text-right' },
      { header: 'Actions', accessor: 'actionsRequired' },
    ];

    this.communicationAgeingCategoryColumns = [
      { header: 'Ageing Category', accessor: 'ageingCategory' },
      { header: 'Count', accessor: 'count', className: 'text-right' },
      { header: '% of Total Failures', accessor: (row) => `${row.percentOfTotalFailures}%`, className: 'text-right' },
      { header: 'Comments', accessor: 'comments' },
    ];

    this.communicationCircleBreakdownColumns = [
      { header: 'Circle', accessor: 'circle' },
      { header: 'Division', accessor: 'division' },
      { header: 'Subdivision', accessor: 'subdivision' },
      { header: 'Total Meters', accessor: 'totalMeters', className: 'text-right' },
      { header: 'Communication Failures', accessor: 'communicationFailures', className: 'text-right' },
      { header: '>30 Days Ageing', accessor: 'ageing30Days', className: 'text-right' },
      { header: 'Never Communicated', accessor: 'neverCommunicated', className: 'text-right' },
      { header: 'Remarks', accessor: 'remarks' },
    ];

    this.communicationMeterDetailColumns = [
      { header: 'Consumer No.', accessor: 'consumerNo', className: 'font-mono text-[#3c83f6]' },
      { header: 'Meter No.', accessor: 'meterNo' },
      { header: 'Circle', accessor: 'circle' },
      { header: 'Last Data Received', accessor: 'lastDataReceived' },
      { header: 'No. of Days Silent', accessor: 'daysSilent', className: 'text-right' },
      { header: 'Comm. Mode', accessor: 'commMode' },
      { header: 'Signal Strength', accessor: 'signalStrength' },
      { header: 'Site Visit Done?', accessor: (row) => ({ status: row.siteVisitDone, variant: row.siteVisitDone === 'Yes' ? 'success' : 'warning' }), className: '' },
      { header: 'Remarks', accessor: 'remarks' },
    ];

    this.communicationRootCauseColumns = [
      { header: 'Root Cause', accessor: 'rootCause' },
      { header: 'No. of Cases', accessor: 'caseCount', className: 'text-right' },
      { header: '%', accessor: (row) => `${row.percentage}%`, className: 'text-right' },
      { header: 'Action Needed', accessor: 'actionNeeded' },
    ];

    this.communicationActionTrackerColumns = [
      { header: 'Circle', accessor: 'circle' },
      { header: 'Category', accessor: 'category' },
      { header: 'Meter Count', accessor: 'meterCount', className: 'text-right' },
      { header: 'Action Owner', accessor: 'actionOwner' },
      { header: 'Deadline', accessor: 'deadline' },
      { header: 'Status', accessor: (row) => ({ status: row.status, variant: this.getStatusVariant(row.status) }), className: '' },
    ];
  }

  getStatusVariant(status: string): 'success' | 'warning' | 'danger' | 'default' | 'info' {
    const lowerStatus = status.toLowerCase();
    if (lowerStatus.includes('working') || lowerStatus.includes('healthy') || lowerStatus.includes('normal') || lowerStatus.includes('communicating')) {
      return 'success';
    }
    if (lowerStatus.includes('pending') || lowerStatus.includes('borderline') || lowerStatus.includes('issue')) {
      return 'warning';
    }
    if (lowerStatus.includes('faulty') || lowerStatus.includes('fail') || lowerStatus.includes('yes')) {
      return 'danger';
    }
    if (lowerStatus.includes('no')) {
      return 'info';
    }
    return 'default';
  }

  // Helper to get zero consumption categories with IDs
  getZeroConsumptionCategoriesWithIds() {
    return this.zeroConsumptionCategories.map((c, i) => ({ ...c, id: String(i) }));
  }

  // Helper to get consumption drop summary with IDs
  getConsumptionDropSummaryWithIds() {
    return this.consumptionDropSummary.map((s, i) => ({ ...s, id: String(i) }));
  }

  // Helper to get low consumption summary with IDs
  getLowConsumptionSummaryWithIds() {
    return this.lowConsumptionSummary.map((s, i) => ({ ...s, id: String(i) }));
  }

  // Helper to get communication ageing categories with IDs
  getCommunicationAgeingCategoriesWithIds() {
    return this.communicationAgeingCategories.map((c, i) => ({ ...c, id: String(i) }));
  }

  // Helper to get communication root causes with IDs
  getCommunicationRootCausesWithIds() {
    return this.communicationRootCauses.map((r, i) => ({ ...r, id: String(i) }));
  }
}

<app-base-page-layout pageTitle="Consumer Data Analysis">
  <!-- Topic 1: Abnormal Consumption Pattern -->
  <app-topic-section title="Abnormal Consumption Pattern" [topicNumber]="1" [defaultOpen]="true" [isOpen]="true" (opened)="onTopicSectionOpened($event)">
    <app-summary-tiles [data]="abnormalConsumptionSummary"></app-summary-tiles>
    <div class="space-y-4">
      <h3 class="text-md font-semibold" [style.color]="'var(--text-primary)'">1.1 High Consumption Cases</h3>
      <app-data-table [data]="highConsumptionCases" [columns]="highConsumptionColumns"></app-data-table>
    </div>
    <div class="space-y-4">
      <h3 class="text-md font-semibold" [style.color]="'var(--text-primary)'">1.2 Low Consumption / Zero Units Cases</h3>
      <app-data-table [data]="lowConsumptionCases" [columns]="lowConsumptionColumns"></app-data-table>
    </div>
    <div class="grid gap-6 lg:grid-cols-2">
      <app-chart-placeholder [title]="'Top 10 Consumers – Sudden Spike'" [type]="'bar'" [data]="spikeChartData"></app-chart-placeholder>
      <app-chart-placeholder [title]="'Top 10 Consumers – Sudden Drop'" [type]="'bar'" [data]="dropChartData"></app-chart-placeholder>
    </div>
  </app-topic-section>

  <!-- Topic 2: Zero Consumption Analysis -->
  <app-topic-section title="Zero Consumption Analysis Report" [topicNumber]="2" (opened)="onTopicSectionOpened($event)">
    <app-summary-tiles [data]="zeroConsumptionMetrics"></app-summary-tiles>
    <div class="space-y-4">
      <h3 class="text-md font-semibold" [style.color]="'var(--text-primary)'">2.1 Categorized Breakdown</h3>
      <app-data-table [data]="getZeroConsumptionCategoriesWithIds()" [columns]="zeroConsumptionCategoryColumns"></app-data-table>
    </div>
    <div class="space-y-4">
      <h3 class="text-md font-semibold" [style.color]="'var(--text-primary)'">2.2 Sample Consumer-wise Data</h3>
      <app-data-table [data]="zeroConsumptionConsumers" [columns]="zeroConsumptionConsumerColumns"></app-data-table>
    </div>
    <div class="grid gap-6 lg:grid-cols-3">
      <app-chart-placeholder [title]="'Root Cause Distribution'" [type]="'pie'" [data]="zeroConsumptionCategories"></app-chart-placeholder>
      <app-chart-placeholder [title]="'Zero Consumption by Circle'" [type]="'bar'" [data]="circleZeroConsumptionData"></app-chart-placeholder>
      <app-chart-placeholder [title]="'Zero Consumption Trend (Monthly)'" [type]="'line'" [data]="zeroConsumptionTrendData"></app-chart-placeholder>
    </div>
    <app-insights-card [insights]="[
      '25% of zero consumption cases are from non-communicating meters.',
      'Repeated cases from North subdivision indicating possible field process issue.',
      '12% cases have meter energy data but not billed – MDMS to UBS sync issue suspected.'
    ]"></app-insights-card>
  </app-topic-section>

  <!-- Topic 3: Consumption Drop Analysis -->
  <app-topic-section title="Consumption Drop Analysis Report – Post Smart Meter Installation" [topicNumber]="3" (opened)="onTopicSectionOpened($event)">
    <app-data-table [data]="getConsumptionDropSummaryWithIds()" [columns]="consumptionDropSummaryColumns"></app-data-table>
    <div class="space-y-4">
      <h3 class="text-md font-semibold" [style.color]="'var(--text-primary)'">3.1 Consumer-Wise Consumption Comparison</h3>
      <app-data-table [data]="consumptionDropConsumers" [columns]="consumptionDropConsumerColumns"></app-data-table>
    </div>
  </app-topic-section>

  <!-- Topic 4: Low Consumption Trend -->
  <app-topic-section title="Low Consumption Trend Report" [topicNumber]="4" (opened)="onTopicSectionOpened($event)">
    <app-data-table [data]="getLowConsumptionSummaryWithIds()" [columns]="lowConsumptionSummaryColumns"></app-data-table>
    <div class="space-y-4">
      <h3 class="text-md font-semibold" [style.color]="'var(--text-primary)'">4.1 Consumer-Wise Analysis</h3>
      <app-data-table [data]="lowConsumptionConsumers" [columns]="lowConsumptionConsumerColumns"></app-data-table>
    </div>
    <app-insights-card [insights]="[
      'Majority of the drops observed in LT Commercial / HT Industrial category.',
      'Possible causes: Consumer energy optimization, Meter under-recording, Load shifting or seasonal impact.',
      'Total of 567 consumers show more than 30% drop YoY.'
    ]"></app-insights-card>
  </app-topic-section>

  <!-- Topic 5: Consumption Lower Than Expected -->
  <app-topic-section title="Consumers with Consumption Lower Than Expected Pattern" [topicNumber]="5" (opened)="onTopicSectionOpened($event)">
    <app-data-table [data]="lowerThanExpectedConsumers" [columns]="lowerThanExpectedColumns"></app-data-table>
    <app-insights-card [insights]="[
      'AMISP to Validate: Check for potential metering issues or communication gaps.',
      'Field Team to Investigate: Physical site inspection where deviation >25%.',
      'Consumer Notification: Alert to be issued in case of recurring anomalies.'
    ]"></app-insights-card>
  </app-topic-section>

  <!-- Topic 6: Consumer Profiling & Bucketing -->
  <app-topic-section title="Consumer Consumption Profiling & Bucketing Report" [topicNumber]="6" (opened)="onTopicSectionOpened($event)">
    <div class="space-y-4">
      <h3 class="text-md font-semibold" [style.color]="'var(--text-primary)'">6.1 Bucketing Logic</h3>
      <app-bucket-logic-table [data]="bucketLogic"></app-bucket-logic-table>
    </div>
    <div class="space-y-4">
      <h3 class="text-md font-semibold" [style.color]="'var(--text-primary)'">6.2 Consumer-Wise Profiling</h3>
      <app-data-table [data]="consumerProfiles" [columns]="consumerProfileColumns"></app-data-table>
    </div>
    <div class="space-y-4">
      <h3 class="text-md font-semibold" [style.color]="'var(--text-primary)'">6.3 Summary by Category & Bucket</h3>
      <app-bucket-summary-table [data]="bucketSummary"></app-bucket-summary-table>
    </div>
    <app-insights-card [insights]="[
      'Prioritize High Risk consumers for inspection and automated alerts.',
      'Issue load enhancement notices where MD consistently exceeds SL.',
      'Investigate zero use consumers with sanctioned load >1 kW.',
      'Update risk categorization monthly or as per data availability.'
    ]"></app-insights-card>
  </app-topic-section>

  <!-- Topic 7: Communication Gap & Ageing Analytics -->
  <app-topic-section title="Communication Gap & Ageing Analytics Report" [topicNumber]="7" (opened)="onTopicSectionOpened($event)">
    <app-summary-tiles [data]="communicationGapSummary"></app-summary-tiles>
    <div class="space-y-4">
      <h3 class="text-md font-semibold" [style.color]="'var(--text-primary)'">7.1 Communication Failure Ageing Category Summary</h3>
      <app-data-table [data]="getCommunicationAgeingCategoriesWithIds()" [columns]="communicationAgeingCategoryColumns"></app-data-table>
    </div>
    <div class="space-y-4">
      <h3 class="text-md font-semibold" [style.color]="'var(--text-primary)'">7.2 Circle / Division Level Breakdown</h3>
      <app-data-table [data]="communicationCircleBreakdown" [columns]="communicationCircleBreakdownColumns"></app-data-table>
    </div>
    <div class="space-y-4">
      <h3 class="text-md font-semibold" [style.color]="'var(--text-primary)'">7.3 Sample Meter-Level Detail (Extract)</h3>
      <app-data-table [data]="communicationMeterDetails" [columns]="communicationMeterDetailColumns"></app-data-table>
    </div>
    <div class="space-y-4">
      <h3 class="text-md font-semibold" [style.color]="'var(--text-primary)'">7.4 Root Cause Classification</h3>
      <app-data-table [data]="getCommunicationRootCausesWithIds()" [columns]="communicationRootCauseColumns"></app-data-table>
    </div>
    <div class="space-y-4">
      <h3 class="text-md font-semibold" [style.color]="'var(--text-primary)'">7.5 Action Tracker – For AMISP</h3>
      <app-data-table [data]="communicationActionTracker" [columns]="communicationActionTrackerColumns"></app-data-table>
    </div>
    <app-insights-card [insights]="[
      '38% of communication failures are due to RF coverage issues - infrastructure upgrade needed.',
      'Meters with >30 days ageing require immediate field intervention.',
      '234 meters never communicated since installation - MDM configuration review required.',
      'Prioritize action tracker items with deadlines approaching within 7 days.'
    ]"></app-insights-card>
  </app-topic-section>
</app-base-page-layout>

// love/src/pages/ConsumerDataAnalysis.tsx
import { MainLayout } from '@/components/layout/MainLayout';
import { TopicSection } from '@/components/consumer-analytics/TopicSection';
import { SummaryTiles } from '@/components/consumer-analytics/SummaryTiles';
import { DataTable } from '@/components/consumer-analytics/DataTable';
import { SpikeDropChart, TrendChart, CategoryPieChart, CircleBarChart } from '@/components/consumer-analytics/ConsumptionCharts';
import { InsightsCard } from '@/components/consumer-analytics/InsightsCard';
import { StatusBadge, getStatusVariant } from '@/components/consumer-analytics/StatusBadge';
import { BucketLogicTable, BucketSummaryTable } from '@/components/consumer-analytics/BucketTable';
import {
  abnormalConsumptionSummary, highConsumptionCases, lowConsumptionCases, spikeChartData, dropChartData,
  zeroConsumptionMetrics, zeroConsumptionCategories, zeroConsumptionConsumers, zeroConsumptionTrendData, circleZeroConsumptionData,
  consumptionDropSummary, consumptionDropConsumers,
  lowConsumptionSummary, lowConsumptionConsumers,
  lowerThanExpectedConsumers,
  dayNightSummary, dayNightConsumers,
  bucketLogic, consumerProfiles, bucketSummary,
} from '@/data/consumerAnalyticsData';

export default function ConsumerDataAnalysis() {
  return (
    <MainLayout title="Consumer Data Analysis">
      <div className="container mx-auto px-6 py-8">
        {/* Topic 1: Abnormal Consumption Pattern */}
        <TopicSection title="Abnormal Consumption Pattern" topicNumber={1} defaultOpen={true}>
          <SummaryTiles data={abnormalConsumptionSummary} />
          <div className="space-y-4">
            <h3 className="text-md font-semibold text-foreground">1.1 High Consumption Cases</h3>
            <DataTable
              data={highConsumptionCases}
              columns={[
                { header: 'Circle', accessor: 'circle' },
                { header: 'Division', accessor: 'division' },
                { header: 'Subdivision', accessor: 'subdivision' },
                { header: 'Consumer No.', accessor: 'consumerNo', className: 'font-mono text-primary' },
                { header: 'Avg (3 mo)', accessor: 'avgConsumption', className: 'text-right' },
                { header: 'Current', accessor: 'currentMonth', className: 'text-right' },
                { header: '% Change', accessor: (row) => <span className="text-emerald-500">+{row.percentChange}%</span>, className: 'text-right' },
                { header: 'Status', accessor: (row) => <StatusBadge status={row.meterStatus} variant={getStatusVariant(row.meterStatus)} /> },
                { header: 'Remarks', accessor: 'remarks' },
              ]}
            />
          </div>
          <div className="space-y-4">
            <h3 className="text-md font-semibold text-foreground">1.2 Low Consumption / Zero Units Cases</h3>
            <DataTable
              data={lowConsumptionCases}
              columns={[
                { header: 'Circle', accessor: 'circle' },
                { header: 'Division', accessor: 'division' },
                { header: 'Subdivision', accessor: 'subdivision' },
                { header: 'Consumer No.', accessor: 'consumerNo', className: 'font-mono text-primary' },
                { header: 'Avg (3 mo)', accessor: 'avgConsumption', className: 'text-right' },
                { header: 'Current', accessor: 'currentMonth', className: 'text-right' },
                { header: '% Change', accessor: (row) => <span className="text-red-500">{row.percentChange}%</span>, className: 'text-right' },
                { header: 'Status', accessor: (row) => <StatusBadge status={row.meterStatus} variant={getStatusVariant(row.meterStatus)} /> },
                { header: 'Remarks', accessor: 'remarks' },
              ]}
            />
          </div>
          <div className="grid gap-6 lg:grid-cols-2">
            <SpikeDropChart data={spikeChartData} type="spike" title="Top 10 Consumers – Sudden Spike" />
            <SpikeDropChart data={dropChartData} type="drop" title="Top 10 Consumers – Sudden Drop" />
          </div>
        </TopicSection>

        {/* Topic 2: Zero Consumption Analysis */}
        <TopicSection title="Zero Consumption Analysis Report" topicNumber={2}>
          <SummaryTiles data={zeroConsumptionMetrics} />
          <div className="space-y-4">
            <h3 className="text-md font-semibold text-foreground">2.1 Categorized Breakdown</h3>
            <DataTable
              data={zeroConsumptionCategories.map((c, i) => ({ ...c, id: String(i) }))}
              columns={[
                { header: 'Category', accessor: 'category' },
                { header: 'Count', accessor: 'count', className: 'text-right' },
                { header: '% of Total', accessor: (row) => `${row.percentage}%`, className: 'text-right' },
                { header: 'Comments', accessor: 'comments' },
              ]}
            />
          </div>
          <div className="space-y-4">
            <h3 className="text-md font-semibold text-foreground">2.2 Sample Consumer-wise Data</h3>
            <DataTable
              data={zeroConsumptionConsumers}
              columns={[
                { header: 'Circle', accessor: 'circle' },
                { header: 'Division', accessor: 'division' },
                { header: 'Consumer No.', accessor: 'consumerNo', className: 'font-mono text-primary' },
                { header: 'Meter Serial', accessor: 'meterSerialNo' },
                { header: 'Last Data', accessor: 'lastDataReceived' },
                { header: 'Last kWh', accessor: 'lastConsumption', className: 'text-right' },
                { header: 'Status', accessor: (row) => <StatusBadge status={row.communicationStatus} variant={getStatusVariant(row.communicationStatus)} /> },
                { header: 'Remarks', accessor: 'remarks' },
              ]}
            />
          </div>
          <div className="grid gap-6 lg:grid-cols-3">
            <CategoryPieChart data={zeroConsumptionCategories} title="Root Cause Distribution" />
            <CircleBarChart data={circleZeroConsumptionData} title="Zero Consumption by Circle" />
            <TrendChart data={zeroConsumptionTrendData} title="Zero Consumption Trend (Monthly)" />
          </div>
          <InsightsCard insights={[
            '25% of zero consumption cases are from non-communicating meters.',
            'Repeated cases from North subdivision indicating possible field process issue.',
            '12% cases have meter energy data but not billed – MDMS to UBS sync issue suspected.',
          ]} />
        </TopicSection>

        {/* Topic 3: Consumption Drop Analysis */}
        <TopicSection title="Consumption Drop Analysis Report – Post Smart Meter Installation" topicNumber={3}>
          <DataTable
            data={consumptionDropSummary.map((s, i) => ({ ...s, id: String(i) }))}
            columns={[
              { header: 'Parameter', accessor: 'parameter' },
              { header: 'Count of Consumers', accessor: 'consumerCount', className: 'text-right' },
              { header: 'Total Drop (kWh)', accessor: 'totalDrop', className: 'text-right' },
              { header: 'Avg. % Drop', accessor: (row) => `${row.avgDropPercent}%`, className: 'text-right text-red-500' },
            ]}
          />
          <div className="space-y-4">
            <h3 className="text-md font-semibold text-foreground">3.1 Consumer-Wise Consumption Comparison</h3>
            <DataTable
              data={consumptionDropConsumers}
              columns={[
                { header: 'S.No', accessor: 'sNo' },
                { header: 'Consumer No.', accessor: 'consumerNo', className: 'font-mono text-primary' },
                { header: 'Name', accessor: 'consumerName' },
                { header: 'Current', accessor: 'currentMonth', className: 'text-right' },
                { header: 'Same Month LY', accessor: 'sameMonthLastYear', className: 'text-right' },
                { header: 'Last Month', accessor: 'lastMonth', className: 'text-right' },
                { header: '% Drop', accessor: (row) => <span className="text-red-500">{row.dropPercent}%</span>, className: 'text-right' },
              ]}
            />
          </div>
        </TopicSection>

        {/* Topic 4: Low Consumption Trend */}
        <TopicSection title="Low Consumption Trend Report" topicNumber={4}>
          <DataTable
            data={lowConsumptionSummary.map((s, i) => ({ ...s, id: String(i) }))}
            columns={[
              { header: 'Category', accessor: 'category' },
              { header: 'No. of Consumers', accessor: 'consumerCount', className: 'text-right' },
              { header: '% of Total', accessor: (row) => row.percentOfTotal > 0 ? `${row.percentOfTotal}%` : '—', className: 'text-right' },
            ]}
          />
          <div className="space-y-4">
            <h3 className="text-md font-semibold text-foreground">4.1 Consumer-Wise Analysis</h3>
            <DataTable
              data={lowConsumptionConsumers}
              columns={[
                { header: 'S.No', accessor: 'sNo' },
                { header: 'Consumer No.', accessor: 'consumerNo', className: 'font-mono text-primary' },
                { header: 'Name', accessor: 'name' },
                { header: 'SL (kW)', accessor: 'sanctionedLoad', className: 'text-right' },
                { header: 'Avg Monthly', accessor: 'avgMonthlyConsumption', className: 'text-right' },
                { header: 'Expected', accessor: 'expectedConsumption', className: 'text-right' },
                { header: '% Deviation', accessor: (row) => <span className="text-red-500">{row.deviation}%</span>, className: 'text-right' },
                { header: 'Status', accessor: (row) => <StatusBadge status={row.meterStatus} variant={getStatusVariant(row.meterStatus)} /> },
              ]}
            />
          </div>
          <InsightsCard insights={[
            'Majority of the drops observed in LT Commercial / HT Industrial category.',
            'Possible causes: Consumer energy optimization, Meter under-recording, Load shifting or seasonal impact.',
            'Total of 567 consumers show more than 30% drop YoY.',
          ]} />
        </TopicSection>

        {/* Topic 5: Consumption Lower Than Expected */}
        <TopicSection title="Consumers with Consumption Lower Than Expected Pattern" topicNumber={5}>
          <DataTable
            data={lowerThanExpectedConsumers}
            columns={[
              { header: 'Sr.No', accessor: 'srNo' },
              { header: 'Consumer No.', accessor: 'consumerNo', className: 'font-mono text-primary' },
              { header: 'Name', accessor: 'consumerName' },
              { header: 'Meter No.', accessor: 'meterNo' },
              { header: 'Avg LY (kWh)', accessor: 'avgMonthlyLastYear', className: 'text-right' },
              { header: 'Current (kWh)', accessor: 'currentMonthConsumption', className: 'text-right' },
              { header: '% Deviation', accessor: (row) => <span className="text-red-500">{row.deviation}%</span>, className: 'text-right' },
              { header: 'Expected Range', accessor: 'expectedRange' },
              { header: 'Remarks', accessor: 'remarks' },
            ]}
          />
          <InsightsCard insights={[
            'AMISP to Validate: Check for potential metering issues or communication gaps.',
            'Field Team to Investigate: Physical site inspection where deviation >25%.',
            'Consumer Notification: Alert to be issued in case of recurring anomalies.',
          ]} />
        </TopicSection>

        {/* Topic 6: Day Use with Zero Night */}
        <TopicSection title="Abnormal Consumption Pattern – Day Use with Zero Night Consumption" topicNumber={6}>
          <SummaryTiles data={dayNightSummary} />
          <div className="space-y-4">
            <h3 className="text-md font-semibold text-foreground">6.1 Consumer-wise Report</h3>
            <DataTable
              data={dayNightConsumers}
              columns={[
                { header: 'S.No', accessor: 'sNo' },
                { header: 'Consumer No.', accessor: 'consumerNo', className: 'font-mono text-primary' },
                { header: 'Name', accessor: 'consumerName' },
                { header: 'Meter No.', accessor: 'meterNo' },
                { header: 'Load (kW)', accessor: 'connectedLoad', className: 'text-right' },
                { header: 'Day (kWh)', accessor: 'dayConsumption', className: 'text-right' },
                { header: 'Night (kWh)', accessor: 'nightConsumption', className: 'text-right' },
                { header: 'Suspicion', accessor: (row) => <StatusBadge status={row.suspicionFlag} variant={getStatusVariant(row.suspicionFlag)} /> },
                { header: 'Remarks', accessor: 'remarks' },
              ]}
            />
          </div>
          <InsightsCard insights={[
            '342 consumers show consistent zero-night consumption despite normal day usage.',
            'Mostly observed in urban slums / high-density residential areas.',
            'Possible bypassing or night-time disconnect of metering circuit.',
          ]} />
        </TopicSection>

        {/* Topic 7: Consumer Profiling & Bucketing */}
        <TopicSection title="Consumer Consumption Profiling & Bucketing Report" topicNumber={7}>
          <div className="space-y-4">
            <h3 className="text-md font-semibold text-foreground">7.1 Bucketing Logic</h3>
            <BucketLogicTable data={bucketLogic} />
          </div>
          <div className="space-y-4">
            <h3 className="text-md font-semibold text-foreground">7.2 Consumer-Wise Profiling</h3>
            <DataTable
              data={consumerProfiles}
              columns={[
                { header: 'S.No', accessor: 'sNo' },
                { header: 'Consumer No.', accessor: 'consumerNo', className: 'font-mono text-primary' },
                { header: 'Name', accessor: 'name' },
                { header: 'Category', accessor: 'category' },
                { header: 'SL (kW)', accessor: 'sanctionedLoad', className: 'text-right' },
                { header: 'Avg MD', accessor: 'avgMD', className: 'text-right' },
                { header: 'Bucket', accessor: (row) => <StatusBadge status={row.bucket} variant={row.bucket.includes('High') ? 'danger' : row.bucket.includes('Medium') ? 'warning' : 'success'} /> },
                { header: 'Tamper', accessor: 'tamperEvents', className: 'text-right' },
                { header: 'Actions', accessor: 'actionsRequired' },
              ]}
            />
          </div>
          <div className="space-y-4">
            <h3 className="text-md font-semibold text-foreground">7.3 Summary by Category & Bucket</h3>
            <BucketSummaryTable data={bucketSummary} />
          </div>
          <InsightsCard insights={[
            'Prioritize High Risk consumers for inspection and automated alerts.',
            'Issue load enhancement notices where MD consistently exceeds SL.',
            'Investigate zero use consumers with sanctioned load >1 kW.',
            'Update risk categorization monthly or as per data availability.',
          ]} />
        </TopicSection>
      </div>
    </MainLayout>
  );
}
