// frontend/src/app/components/data-table/data-table.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { StatusBadgeComponent } from '../status-badge/status-badge.component';

export interface Column<T = any> {
  header: string;
  accessor: keyof T | ((row: T) => any);
  className?: string;
}

@Component({
  selector: 'app-data-table',
  standalone: true,
  imports: [CommonModule, StatusBadgeComponent],
  templateUrl: './data-table.component.html',
  styleUrl: './data-table.component.css'
})
export class DataTableComponent<T extends { id: string }> {
  @Input() columns: Column<T>[] = [];
  @Input() data: T[] = [];
  @Input() className: string = '';

  getCellValue(row: T, accessor: Column<T>['accessor']): any {
    if (typeof accessor === 'function') {
      return accessor(row);
    }
    const value = row[accessor as keyof T];
    if (typeof value === 'number') {
      return value.toLocaleString();
    }
    return value;
  }

  isStatusBadge(value: any): boolean {
    return value && typeof value === 'object' && 'status' in value && 'variant' in value;
  }

  isStringOrNumber(value: any): boolean {
    return typeof value === 'string' || typeof value === 'number';
  }
}

<div [class]="'overflow-x-auto rounded-xl border bg-card ' + className" [style.border-color]="'var(--border-color)'" [style.background-color]="'var(--bg-card)'">
  <table class="w-full text-sm">
    <thead>
      <tr [style.border-bottom-color]="'var(--border-color)'" [style.background-color]="'var(--bg-card-hover)'">
        <th
          *ngFor="let col of columns"
          [class]="'px-4 py-3 text-left font-semibold whitespace-nowrap ' + (col.className || '')"
          [style.color]="'var(--text-primary)'"
        >
          {{ col.header }}
        </th>
      </tr>
    </thead>
    <tbody>
      <tr
        *ngFor="let row of data; let i = index"
        [style.border-bottom-color]="'var(--border-color)'"
        [style.background-color]="i % 2 === 0 ? 'transparent' : 'var(--bg-card)'"
        class="hover:opacity-80 transition-colors"
      >
        <td
          *ngFor="let col of columns"
          [class]="'px-4 py-3 whitespace-nowrap ' + (col.className || '')"
          [style.color]="'var(--text-primary)'"
        >
          <ng-container *ngIf="getCellValue(row, col.accessor) as cellValue">
            <span *ngIf="isStringOrNumber(cellValue)">{{ cellValue }}</span>
            <app-status-badge 
              *ngIf="isStatusBadge(cellValue)" 
              [status]="cellValue.status" 
              [variant]="cellValue.variant">
            </app-status-badge>
          </ng-container>
        </td>
      </tr>
    </tbody>
  </table>
</div>

// love/src/components/consumer-analytics/DataTable.tsx
import { cn } from '@/lib/utils';

interface Column<T> {
  header: string;
  accessor: keyof T | ((row: T) => React.ReactNode);
  className?: string;
}

interface DataTableProps<T> {
  columns: Column<T>[];
  data: T[];
  className?: string;
}

export function DataTable<T extends { id: string }>({ columns, data, className }: DataTableProps<T>) {
  const getCellValue = (row: T, accessor: Column<T>['accessor']) => {
    if (typeof accessor === 'function') {
      return accessor(row);
    }
    const value = row[accessor];
    if (typeof value === 'number') {
      return value.toLocaleString();
    }
    return value as React.ReactNode;
  };

  return (
    <div className={cn("overflow-x-auto rounded-xl border border-border bg-card", className)}>
      <table className="w-full text-sm">
        <thead>
          <tr className="border-b border-border bg-muted/50">
            {columns.map((col, index) => (
              <th
                key={index}
                className={cn(
                  "px-4 py-3 text-left font-semibold text-foreground whitespace-nowrap",
                  col.className
                )}
              >
                {col.header}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {data.map((row, rowIndex) => (
            <tr
              key={row.id}
              className={cn(
                "border-b border-border/50 hover:bg-muted/30 transition-colors",
                rowIndex % 2 === 0 ? "bg-transparent" : "bg-muted/10"
              )}
            >
              {columns.map((col, colIndex) => (
                <td
                  key={colIndex}
                  className={cn("px-4 py-3 whitespace-nowrap", col.className)}
                >
                  {getCellValue(row, col.accessor)}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
