// frontend/src/app/components/summary-tiles/summary-tiles.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

export interface SummaryTile {
  label: string;
  value: number | string;
}

@Component({
  selector: 'app-summary-tiles',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './summary-tiles.component.html',
  styleUrl: './summary-tiles.component.css'
})
export class SummaryTilesComponent {
  @Input() data: SummaryTile[] = [];

  formatValue(value: number | string): string {
    if (typeof value === 'number') {
      return value.toLocaleString();
    }
    return value;
  }
}

<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-4">
  <div *ngFor="let item of data" class="bg-card border rounded-xl p-4 transition-colors hover:border-accent/50" [style.border-color]="'var(--border-color)'" [style.background-color]="'var(--bg-card)'">
    <div class="flex items-start justify-between">
      <div class="flex-1">
        <p class="text-sm mb-1" [style.color]="'var(--text-secondary)'">{{ item.label }}</p>
        <p class="text-2xl font-bold" [style.color]="'var(--text-primary)'">
          {{ formatValue(item.value) }}
        </p>
      </div>
    </div>
  </div>
</div>

// love/src/components/consumer-analytics/SummaryTiles.tsx
import { cn } from '@/lib/utils';
import { LucideIcon } from 'lucide-react';

interface SummaryTile {
  label: string;
  value: number | string;
}

interface SummaryTilesProps {
  data: SummaryTile[];
  icon?: LucideIcon;
  className?: string;
}

export function SummaryTiles({ data, icon: Icon, className }: SummaryTilesProps) {
  return (
    <div className={cn("grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-4", className)}>
      {data.map((item, index) => (
        <div
          key={index}
          className="bg-card border border-border rounded-xl p-4 hover:border-primary/50 transition-colors"
        >
          <div className="flex items-start justify-between">
            <div className="flex-1">
              <p className="text-sm text-muted-foreground mb-1">{item.label}</p>
              <p className="text-2xl font-bold text-foreground">
                {typeof item.value === 'number' ? item.value.toLocaleString() : item.value}
              </p>
            </div>
            {Icon && <Icon className="h-5 w-5 text-primary shrink-0" />}
          </div>
        </div>
      ))}
    </div>
  );
}
