// frontend/src/app/components/topic-section/topic-section.component.ts
import { Component, Input, OnInit, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-topic-section',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './topic-section.component.html',
  styleUrl: './topic-section.component.css'
})
export class TopicSectionComponent implements OnInit {
  @Input() title: string = '';
  @Input() topicNumber: number = 1;
  @Input() defaultOpen: boolean = false;
  @Input() isOpen: boolean = false;
  @Output() opened = new EventEmitter<TopicSectionComponent>();
  
  ngOnInit() {
    if (this.defaultOpen && !this.isOpen) {
      this.isOpen = true;
    }
  }

  toggle() {
    if (!this.isOpen) {
      // Emit event to parent to close other sections
      this.opened.emit(this);
    }
    this.isOpen = !this.isOpen;
  }

  close() {
    this.isOpen = false;
  }
}

<section class="mb-6 animate-fade-in">
  <button
    (click)="toggle()"
    class="w-full flex items-center justify-between p-4 bg-card border border-theme rounded-xl hover:border-accent/50 transition-colors"
    [style.background-color]="'var(--bg-card)'"
    [style.border-color]="'var(--border-color)'"
  >
    <div class="flex items-center gap-3">
      <span class="flex items-center justify-center w-8 h-8 rounded-lg text-white font-bold text-sm" [style.background-color]="'var(--accent-color)'">
        {{ topicNumber }}
      </span>
      <h2 class="text-lg font-semibold" [style.color]="'var(--text-primary)'">{{ title }}</h2>
    </div>
    <svg *ngIf="isOpen" class="h-5 w-5" [style.color]="'var(--text-secondary)'" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 15l7-7 7 7"></path>
    </svg>
    <svg *ngIf="!isOpen" class="h-5 w-5" [style.color]="'var(--text-secondary)'" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
    </svg>
  </button>
  
  <div [class]="'overflow-hidden transition-all duration-300 ' + (isOpen ? 'mt-4 max-h-[5000px] opacity-100' : 'max-h-0 opacity-0')">
    <div class="space-y-6">
      <ng-content></ng-content>
    </div>
  </div>
</section>

// love/src/components/consumer-analytics/TopicSection.tsx
import { useState } from 'react';
import { ChevronDown, ChevronUp } from 'lucide-react';
import { cn } from '@/lib/utils';

interface TopicSectionProps {
  title: string;
  topicNumber: number;
  children: React.ReactNode;
  defaultOpen?: boolean;
}

export function TopicSection({ title, topicNumber, children, defaultOpen = false }: TopicSectionProps) {
  const [isOpen, setIsOpen] = useState(defaultOpen);

  return (
    <section className="mb-6 animate-fade-in">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full flex items-center justify-between p-4 bg-card border border-border rounded-xl hover:border-primary/50 transition-colors"
      >
        <div className="flex items-center gap-3">
          <span className="flex items-center justify-center w-8 h-8 rounded-lg bg-primary text-primary-foreground font-bold text-sm">
            {topicNumber}
          </span>
          <h2 className="text-lg font-semibold text-foreground">{title}</h2>
        </div>
        {isOpen ? (
          <ChevronUp className="h-5 w-5 text-muted-foreground" />
        ) : (
          <ChevronDown className="h-5 w-5 text-muted-foreground" />
        )}
      </button>
      
      <div className={cn(
        "overflow-hidden transition-all duration-300",
        isOpen ? "mt-4 max-h-[5000px] opacity-100" : "max-h-0 opacity-0"
      )}>
        <div className="space-y-6">
          {children}
        </div>
      </div>
    </section>
  );
}
